[package]
name = "wacc"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
itertools = "0.10"
once_cell = "1.15"
clap = { version = "4.0", features = ["derive"] }
color-eyre = "0.6"
slotmap = "1.0"
elsa = "1.7"
